// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID         int64
	LinkID     int64
	ClickedAt  pgtype.Timestamptz
	IpHash     string
	Referrer   pgtype.Text
	UserAgent  pgtype.Text
	DeviceType pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	Country    pgtype.Text
	City       pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Link struct {
	ID             int64
	ShortCode      string
	OriginalUrl    string
	OwnershipToken string
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Active         bool
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Revoked   pgtype.Bool
}

type User struct {
	ID              int64
	Email           string
	PasswordHash    pgtype.Text
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
	CreatedAt       pgtype.Timestamptz
}
