// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID         int64
	LinkID     int64
	ClickedAt  pgtype.Timestamptz
	IpHash     pgtype.Text
	Referrer   pgtype.Text
	UserAgent  pgtype.Text
	DeviceType pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	Country    pgtype.Text
	City       pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Link struct {
	ID             int64
	PublicUserID   pgtype.UUID
	ShortCode      string
	OriginalUrl    string
	OwnershipToken pgtype.Text
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	Active         bool
}

type LoginAttempt struct {
	UserID      int64
	FailCount   int32
	Tier        int32
	LockedUntil pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Otp struct {
	ID           int64
	UserPublicID pgtype.UUID
	Purpose      string
	Code         string
	Revoked      bool
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Revoked   bool
}

type User struct {
	ID              int64
	PublicID        pgtype.UUID
	Email           string
	Password        pgtype.Text
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}
