// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :exec
INSERT INTO otp (
	code, expires_at, purpose, revoked, user_public_id
) VALUES (
	$1, $2, $3, $4, $5
)
`

type CreateOTPParams struct {
	Code         string
	ExpiresAt    pgtype.Timestamptz
	Purpose      string
	Revoked      bool
	UserPublicID pgtype.UUID
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, createOTP,
		arg.Code,
		arg.ExpiresAt,
		arg.Purpose,
		arg.Revoked,
		arg.UserPublicID,
	)
	return err
}

const getClicksByLinkIDAndClickedAt = `-- name: GetClicksByLinkIDAndClickedAt :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id = $1 AND clicked_at = $2
ORDER BY clicked_at
LIMIT 50
`

type GetClicksByLinkIDAndClickedAtParams struct {
	LinkID    int64
	ClickedAt pgtype.Timestamptz
}

func (q *Queries) GetClicksByLinkIDAndClickedAt(ctx context.Context, arg GetClicksByLinkIDAndClickedAtParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndClickedAt, arg.LinkID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByLinkIDAndCountry = `-- name: GetClicksByLinkIDAndCountry :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id= $1 AND country = $2
ORDER BY clicked_at
LIMIT 50
`

type GetClicksByLinkIDAndCountryParams struct {
	LinkID  int64
	Country pgtype.Text
}

func (q *Queries) GetClicksByLinkIDAndCountry(ctx context.Context, arg GetClicksByLinkIDAndCountryParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndCountry, arg.LinkID, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredShortLinkByUserID = `-- name: GetExpiredShortLinkByUserID :many
SELECT id, user_id, short_code, original_url, ownership_token FROM links
WHERE
	user_id=$1 AND expires_at IS NOT NULL AND expires_at < NOW()
ORDER BY created_at
LIMIT 50
`

type GetExpiredShortLinkByUserIDRow struct {
	ID             int64
	UserID         int64
	ShortCode      string
	OriginalUrl    string
	OwnershipToken string
}

func (q *Queries) GetExpiredShortLinkByUserID(ctx context.Context, userID int64) ([]GetExpiredShortLinkByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExpiredShortLinkByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredShortLinkByUserIDRow
	for rows.Next() {
		var i GetExpiredShortLinkByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.OwnershipToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOTPByCodeAndUserID = `-- name: GetOTPByCodeAndUserID :one
SELECT code, user_public_id, revoked, expires_at FROM otp
WHERE
	user_public_id=$1 AND code=$2 AND purpose=$3
LIMIT 1
`

type GetOTPByCodeAndUserIDParams struct {
	UserPublicID pgtype.UUID
	Code         string
	Purpose      string
}

type GetOTPByCodeAndUserIDRow struct {
	Code         string
	UserPublicID pgtype.UUID
	Revoked      bool
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) GetOTPByCodeAndUserID(ctx context.Context, arg GetOTPByCodeAndUserIDParams) (GetOTPByCodeAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOTPByCodeAndUserID, arg.UserPublicID, arg.Code, arg.Purpose)
	var i GetOTPByCodeAndUserIDRow
	err := row.Scan(
		&i.Code,
		&i.UserPublicID,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT id, user_id, token, expires_at, created_at, revoked FROM refresh_tokens
WHERE
	token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const getShortLinkByCode = `-- name: GetShortLinkByCode :one
SELECT id, user_id, short_code, original_url, ownership_token FROM links
WHERE
	short_code = $1
`

type GetShortLinkByCodeRow struct {
	ID             int64
	UserID         int64
	ShortCode      string
	OriginalUrl    string
	OwnershipToken string
}

func (q *Queries) GetShortLinkByCode(ctx context.Context, shortCode string) (GetShortLinkByCodeRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkByCode, shortCode)
	var i GetShortLinkByCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByOauthID = `-- name: GetUserByOauthID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	oauth_provider = $1 AND oauth_provider_id = $2
`

type GetUserByOauthIDParams struct {
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
}

func (q *Queries) GetUserByOauthID(ctx context.Context, arg GetUserByOauthIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOauthID, arg.OauthProvider, arg.OauthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	public_id = $1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeAllOTPsForUser = `-- name: RevokeAllOTPsForUser :exec
UPDATE otp SET revoked = TRUE
WHERE user_public_id=$1 AND purpose=$2 AND revoked=FALSE
`

type RevokeAllOTPsForUserParams struct {
	UserPublicID pgtype.UUID
	Purpose      string
}

func (q *Queries) RevokeAllOTPsForUser(ctx context.Context, arg RevokeAllOTPsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllOTPsForUser, arg.UserPublicID, arg.Purpose)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET
	revoked = TRUE
WHERE
	token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}

const saveNewClick = `-- name: SaveNewClick :one
INSERT INTO clicks (
	link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at
`

type SaveNewClickParams struct {
	LinkID     int64
	ClickedAt  pgtype.Timestamptz
	IpHash     pgtype.Text
	Referrer   pgtype.Text
	UserAgent  pgtype.Text
	DeviceType pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	Country    pgtype.Text
	City       pgtype.Text
}

func (q *Queries) SaveNewClick(ctx context.Context, arg SaveNewClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, saveNewClick,
		arg.LinkID,
		arg.ClickedAt,
		arg.IpHash,
		arg.Referrer,
		arg.UserAgent,
		arg.DeviceType,
		arg.Browser,
		arg.Os,
		arg.Country,
		arg.City,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ClickedAt,
		&i.IpHash,
		&i.Referrer,
		&i.UserAgent,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (
	user_id, token, expires_at, revoked, created_at
) VALUES (
	$1, $2, $3, $4, $5
)
`

type SaveRefreshTokenParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.Revoked,
		arg.CreatedAt,
	)
	return err
}

const saveShortLink = `-- name: SaveShortLink :one
INSERT INTO links (
	user_id, short_code, original_url, ownership_token, expires_at
) VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, user_id, short_code, original_url, ownership_token, created_at, expires_at, active
`

type SaveShortLinkParams struct {
	UserID         int64
	ShortCode      string
	OriginalUrl    string
	OwnershipToken string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) SaveShortLink(ctx context.Context, arg SaveShortLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, saveShortLink,
		arg.UserID,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.OwnershipToken,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users (
	email, password, oauth_provider, oauth_provider_id
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at
`

type SaveUserParams struct {
	Email           string
	Password        pgtype.Text
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.Email,
		arg.Password,
		arg.OauthProvider,
		arg.OauthProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
