// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :exec
INSERT INTO otp (
	code, expires_at, purpose, revoked, user_public_id
) VALUES (
	$1, $2, $3, $4, $5
)
`

type CreateOTPParams struct {
	Code         string
	ExpiresAt    pgtype.Timestamptz
	Purpose      string
	Revoked      bool
	UserPublicID pgtype.UUID
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, createOTP,
		arg.Code,
		arg.ExpiresAt,
		arg.Purpose,
		arg.Revoked,
		arg.UserPublicID,
	)
	return err
}

const getClicksByLinkIDAndClickedAt = `-- name: GetClicksByLinkIDAndClickedAt :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id = $1 AND clicked_at = $2
ORDER BY clicked_at
LIMIT 50
`

type GetClicksByLinkIDAndClickedAtParams struct {
	LinkID    int64
	ClickedAt pgtype.Timestamptz
}

func (q *Queries) GetClicksByLinkIDAndClickedAt(ctx context.Context, arg GetClicksByLinkIDAndClickedAtParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndClickedAt, arg.LinkID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByLinkIDAndCountry = `-- name: GetClicksByLinkIDAndCountry :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id= $1 AND country = $2
ORDER BY clicked_at
LIMIT 50
`

type GetClicksByLinkIDAndCountryParams struct {
	LinkID  int64
	Country pgtype.Text
}

func (q *Queries) GetClicksByLinkIDAndCountry(ctx context.Context, arg GetClicksByLinkIDAndCountryParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndCountry, arg.LinkID, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredShortLinkByUserID = `-- name: GetExpiredShortLinkByUserID :many
SELECT id, public_user_id, short_code, original_url, ownership_token FROM links
WHERE
	public_user_id=$1 AND expires_at IS NOT NULL AND expires_at < NOW()
ORDER BY created_at
LIMIT 50
`

type GetExpiredShortLinkByUserIDRow struct {
	ID             int64
	PublicUserID   pgtype.UUID
	ShortCode      string
	OriginalUrl    string
	OwnershipToken pgtype.Text
}

func (q *Queries) GetExpiredShortLinkByUserID(ctx context.Context, publicUserID pgtype.UUID) ([]GetExpiredShortLinkByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExpiredShortLinkByUserID, publicUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredShortLinkByUserIDRow
	for rows.Next() {
		var i GetExpiredShortLinkByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicUserID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.OwnershipToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginAttempt = `-- name: GetLoginAttempt :one
SELECT fail_count, tier, locked_until, updated_at FROM login_attempts WHERE user_id=$1
`

type GetLoginAttemptRow struct {
	FailCount   int32
	Tier        int32
	LockedUntil pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetLoginAttempt(ctx context.Context, userID int64) (GetLoginAttemptRow, error) {
	row := q.db.QueryRow(ctx, getLoginAttempt, userID)
	var i GetLoginAttemptRow
	err := row.Scan(
		&i.FailCount,
		&i.Tier,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const getOTPByCodeAndUserID = `-- name: GetOTPByCodeAndUserID :one
SELECT u.id, u.public_id, u.email, u.created_at, o.code, o.revoked, o.expires_at
FROM otp AS o
INNER JOIN users AS u
ON o.user_public_id = u.public_id
WHERE
	user_public_id=$1 AND code=$2 AND purpose=$3
LIMIT 1
`

type GetOTPByCodeAndUserIDParams struct {
	UserPublicID pgtype.UUID
	Code         string
	Purpose      string
}

type GetOTPByCodeAndUserIDRow struct {
	ID        int64
	PublicID  pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
	Code      string
	Revoked   bool
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetOTPByCodeAndUserID(ctx context.Context, arg GetOTPByCodeAndUserIDParams) (GetOTPByCodeAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOTPByCodeAndUserID, arg.UserPublicID, arg.Code, arg.Purpose)
	var i GetOTPByCodeAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.CreatedAt,
		&i.Code,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
SELECT u.id, u.public_id, r.token, r.expires_at, r.revoked
FROM refresh_tokens AS r
INNER JOIN users AS u
ON r.user_id = u.id
WHERE
	r.token = $1
`

type GetRefreshTokenByTokenRow struct {
	ID        int64
	PublicID  pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
}

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (GetRefreshTokenByTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByToken, token)
	var i GetRefreshTokenByTokenRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getShortLinkByCode = `-- name: GetShortLinkByCode :one
SELECT id, public_user_id, short_code, original_url, ownership_token FROM links
WHERE
	short_code = $1
`

type GetShortLinkByCodeRow struct {
	ID             int64
	PublicUserID   pgtype.UUID
	ShortCode      string
	OriginalUrl    string
	OwnershipToken pgtype.Text
}

func (q *Queries) GetShortLinkByCode(ctx context.Context, shortCode string) (GetShortLinkByCodeRow, error) {
	row := q.db.QueryRow(ctx, getShortLinkByCode, shortCode)
	var i GetShortLinkByCodeRow
	err := row.Scan(
		&i.ID,
		&i.PublicUserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByOauthProviderAndOauthID = `-- name: GetUserByOauthProviderAndOauthID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	oauth_provider = $1 AND oauth_provider_id = $2
`

type GetUserByOauthProviderAndOauthIDParams struct {
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
}

func (q *Queries) GetUserByOauthProviderAndOauthID(ctx context.Context, arg GetUserByOauthProviderAndOauthIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOauthProviderAndOauthID, arg.OauthProvider, arg.OauthProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at FROM users
WHERE
	public_id = $1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const linkOAuthUser = `-- name: LinkOAuthUser :one
UPDATE users SET oauth_provider = $1, oauth_provider_id = $2
WHERE email = $3
RETURNING email, public_id, oauth_provider, oauth_provider_id, created_at
`

type LinkOAuthUserParams struct {
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
	Email           string
}

type LinkOAuthUserRow struct {
	Email           string
	PublicID        pgtype.UUID
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) LinkOAuthUser(ctx context.Context, arg LinkOAuthUserParams) (LinkOAuthUserRow, error) {
	row := q.db.QueryRow(ctx, linkOAuthUser, arg.OauthProvider, arg.OauthProviderID, arg.Email)
	var i LinkOAuthUserRow
	err := row.Scan(
		&i.Email,
		&i.PublicID,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :exec
DELETE FROM login_attempts WHERE user_id=$1
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetLoginAttempts, userID)
	return err
}

const revokeAllOTPsForUser = `-- name: RevokeAllOTPsForUser :exec
UPDATE otp SET revoked = TRUE
WHERE user_public_id=$1 AND purpose=$2 AND revoked=FALSE
`

type RevokeAllOTPsForUserParams struct {
	UserPublicID pgtype.UUID
	Purpose      string
}

func (q *Queries) RevokeAllOTPsForUser(ctx context.Context, arg RevokeAllOTPsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllOTPsForUser, arg.UserPublicID, arg.Purpose)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE user_id=$1
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET
	revoked = TRUE
WHERE
	token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}

const saveNewClick = `-- name: SaveNewClick :one
INSERT INTO clicks (
	link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at
`

type SaveNewClickParams struct {
	LinkID     int64
	ClickedAt  pgtype.Timestamptz
	IpHash     pgtype.Text
	Referrer   pgtype.Text
	UserAgent  pgtype.Text
	DeviceType pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	Country    pgtype.Text
	City       pgtype.Text
}

func (q *Queries) SaveNewClick(ctx context.Context, arg SaveNewClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, saveNewClick,
		arg.LinkID,
		arg.ClickedAt,
		arg.IpHash,
		arg.Referrer,
		arg.UserAgent,
		arg.DeviceType,
		arg.Browser,
		arg.Os,
		arg.Country,
		arg.City,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ClickedAt,
		&i.IpHash,
		&i.Referrer,
		&i.UserAgent,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (
	user_id, token, expires_at, revoked, created_at
) VALUES (
	$1, $2, $3, $4, $5
)
`

type SaveRefreshTokenParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.Revoked,
		arg.CreatedAt,
	)
	return err
}

const saveShortLink = `-- name: SaveShortLink :one
INSERT INTO links (
	public_user_id, short_code, original_url, ownership_token, expires_at
) VALUES (
	$1, $2, $3, $4, $5
)
RETURNING id, public_user_id, short_code, original_url, ownership_token, created_at, expires_at, active
`

type SaveShortLinkParams struct {
	PublicUserID   pgtype.UUID
	ShortCode      string
	OriginalUrl    string
	OwnershipToken pgtype.Text
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) SaveShortLink(ctx context.Context, arg SaveShortLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, saveShortLink,
		arg.PublicUserID,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.OwnershipToken,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.PublicUserID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO users (
	email, password, oauth_provider, oauth_provider_id
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, public_id, email, password, oauth_provider, oauth_provider_id, created_at, deleted_at
`

type SaveUserParams struct {
	Email           string
	Password        pgtype.Text
	OauthProvider   pgtype.Text
	OauthProviderID pgtype.Text
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, saveUser,
		arg.Email,
		arg.Password,
		arg.OauthProvider,
		arg.OauthProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Password,
		&i.OauthProvider,
		&i.OauthProviderID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertLoginAttempt = `-- name: UpsertLoginAttempt :exec
INSERT INTO login_attempts (user_id, fail_count, tier, locked_until, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE SET
fail_count=$2, tier=$3, locked_until=$4, updated_at=NOW()
`

type UpsertLoginAttemptParams struct {
	UserID      int64
	FailCount   int32
	Tier        int32
	LockedUntil pgtype.Timestamptz
}

func (q *Queries) UpsertLoginAttempt(ctx context.Context, arg UpsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, upsertLoginAttempt,
		arg.UserID,
		arg.FailCount,
		arg.Tier,
		arg.LockedUntil,
	)
	return err
}
