// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClicksByLinkIDAndClickedAt = `-- name: GetClicksByLinkIDAndClickedAt :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id = $1 AND clicked_at = $2
`

type GetClicksByLinkIDAndClickedAtParams struct {
	LinkID    int64
	ClickedAt pgtype.Timestamptz
}

func (q *Queries) GetClicksByLinkIDAndClickedAt(ctx context.Context, arg GetClicksByLinkIDAndClickedAtParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndClickedAt, arg.LinkID, arg.ClickedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByLinkIDAndCountry = `-- name: GetClicksByLinkIDAndCountry :many
SELECT id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at FROM clicks
WHERE
	link_id= $1 AND country = $2
`

type GetClicksByLinkIDAndCountryParams struct {
	LinkID  int64
	Country pgtype.Text
}

func (q *Queries) GetClicksByLinkIDAndCountry(ctx context.Context, arg GetClicksByLinkIDAndCountryParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkIDAndCountry, arg.LinkID, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Click
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.IpHash,
			&i.Referrer,
			&i.UserAgent,
			&i.DeviceType,
			&i.Browser,
			&i.Os,
			&i.Country,
			&i.City,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortLinkByCode = `-- name: GetShortLinkByCode :one
SELECT id, short_code, original_url, ownership_token, created_at, expires_at, active FROM links
WHERE
	short_code = $1
`

func (q *Queries) GetShortLinkByCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getShortLinkByCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const getShortLinkByExpiresAt = `-- name: GetShortLinkByExpiresAt :many
SELECT id, short_code, original_url, ownership_token, created_at, expires_at, active FROM links
WHERE
	expires_at IS NOT NULL
`

func (q *Queries) GetShortLinkByExpiresAt(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, getShortLinkByExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.OwnershipToken,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNewClick = `-- name: SaveNewClick :one
INSERT INTO clicks (
	link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, link_id, clicked_at, ip_hash, referrer, user_agent, device_type, browser, os, country, city, created_at
`

type SaveNewClickParams struct {
	LinkID     int64
	ClickedAt  pgtype.Timestamptz
	IpHash     string
	Referrer   pgtype.Text
	UserAgent  pgtype.Text
	DeviceType pgtype.Text
	Browser    pgtype.Text
	Os         pgtype.Text
	Country    pgtype.Text
	City       pgtype.Text
}

func (q *Queries) SaveNewClick(ctx context.Context, arg SaveNewClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, saveNewClick,
		arg.LinkID,
		arg.ClickedAt,
		arg.IpHash,
		arg.Referrer,
		arg.UserAgent,
		arg.DeviceType,
		arg.Browser,
		arg.Os,
		arg.Country,
		arg.City,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ClickedAt,
		&i.IpHash,
		&i.Referrer,
		&i.UserAgent,
		&i.DeviceType,
		&i.Browser,
		&i.Os,
		&i.Country,
		&i.City,
		&i.CreatedAt,
	)
	return i, err
}

const saveShortLink = `-- name: SaveShortLink :one
INSERT INTO links (
	short_code, original_url, ownership_token, expires_at
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, short_code, original_url, ownership_token, created_at, expires_at, active
`

type SaveShortLinkParams struct {
	ShortCode      string
	OriginalUrl    string
	OwnershipToken string
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) SaveShortLink(ctx context.Context, arg SaveShortLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, saveShortLink,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.OwnershipToken,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.OwnershipToken,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}
