// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetClicksByLinkIDAndClickedAt(ctx context.Context, arg GetClicksByLinkIDAndClickedAtParams) ([]Click, error)
	GetClicksByLinkIDAndCountry(ctx context.Context, arg GetClicksByLinkIDAndCountryParams) ([]Click, error)
	GetRefreshTokenByToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetShortLinkByCode(ctx context.Context, shortCode string) (Link, error)
	GetShortLinkByExpiresAt(ctx context.Context) ([]Link, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByOauthID(ctx context.Context, arg GetUserByOauthIDParams) (User, error)
	SaveNewClick(ctx context.Context, arg SaveNewClickParams) (Click, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	SaveShortLink(ctx context.Context, arg SaveShortLinkParams) (Link, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
