// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockusecases creates a new instance of Mockusecases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockusecases(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockusecases {
	mock := &Mockusecases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockusecases is an autogenerated mock type for the usecases type
type Mockusecases struct {
	mock.Mock
}

type Mockusecases_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockusecases) EXPECT() *Mockusecases_Expecter {
	return &Mockusecases_Expecter{mock: &_m.Mock}
}

// CreateUserEmailPassword provides a mock function for the type Mockusecases
func (_mock *Mockusecases) CreateUserEmailPassword(ctx context.Context, input *dto.EmailPasswordUserInput) (*dto.OTPRequiredResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserEmailPassword")
	}

	var r0 *dto.OTPRequiredResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.EmailPasswordUserInput) (*dto.OTPRequiredResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.EmailPasswordUserInput) *dto.OTPRequiredResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OTPRequiredResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.EmailPasswordUserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockusecases_CreateUserEmailPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserEmailPassword'
type Mockusecases_CreateUserEmailPassword_Call struct {
	*mock.Call
}

// CreateUserEmailPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dto.EmailPasswordUserInput
func (_e *Mockusecases_Expecter) CreateUserEmailPassword(ctx interface{}, input interface{}) *Mockusecases_CreateUserEmailPassword_Call {
	return &Mockusecases_CreateUserEmailPassword_Call{Call: _e.mock.On("CreateUserEmailPassword", ctx, input)}
}

func (_c *Mockusecases_CreateUserEmailPassword_Call) Run(run func(ctx context.Context, input *dto.EmailPasswordUserInput)) *Mockusecases_CreateUserEmailPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.EmailPasswordUserInput
		if args[1] != nil {
			arg1 = args[1].(*dto.EmailPasswordUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockusecases_CreateUserEmailPassword_Call) Return(oTPRequiredResponse *dto.OTPRequiredResponse, err error) *Mockusecases_CreateUserEmailPassword_Call {
	_c.Call.Return(oTPRequiredResponse, err)
	return _c
}

func (_c *Mockusecases_CreateUserEmailPassword_Call) RunAndReturn(run func(ctx context.Context, input *dto.EmailPasswordUserInput) (*dto.OTPRequiredResponse, error)) *Mockusecases_CreateUserEmailPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type Mockusecases
func (_mock *Mockusecases) HealthCheck(ctx context.Context) map[string]bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 map[string]bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]bool); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}
	return r0
}

// Mockusecases_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type Mockusecases_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mockusecases_Expecter) HealthCheck(ctx interface{}) *Mockusecases_HealthCheck_Call {
	return &Mockusecases_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *Mockusecases_HealthCheck_Call) Run(run func(ctx context.Context)) *Mockusecases_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mockusecases_HealthCheck_Call) Return(stringToBool map[string]bool) *Mockusecases_HealthCheck_Call {
	_c.Call.Return(stringToBool)
	return _c
}

func (_c *Mockusecases_HealthCheck_Call) RunAndReturn(run func(ctx context.Context) map[string]bool) *Mockusecases_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type Mockusecases
func (_mock *Mockusecases) Login(ctx context.Context, input *dto.LoginInput) (*dto.OTPRequiredResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.OTPRequiredResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginInput) (*dto.OTPRequiredResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.LoginInput) *dto.OTPRequiredResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OTPRequiredResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.LoginInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockusecases_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Mockusecases_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dto.LoginInput
func (_e *Mockusecases_Expecter) Login(ctx interface{}, input interface{}) *Mockusecases_Login_Call {
	return &Mockusecases_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *Mockusecases_Login_Call) Run(run func(ctx context.Context, input *dto.LoginInput)) *Mockusecases_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.LoginInput
		if args[1] != nil {
			arg1 = args[1].(*dto.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockusecases_Login_Call) Return(oTPRequiredResponse *dto.OTPRequiredResponse, err error) *Mockusecases_Login_Call {
	_c.Call.Return(oTPRequiredResponse, err)
	return _c
}

func (_c *Mockusecases_Login_Call) RunAndReturn(run func(ctx context.Context, input *dto.LoginInput) (*dto.OTPRequiredResponse, error)) *Mockusecases_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type Mockusecases
func (_mock *Mockusecases) RefreshAccessToken(ctx context.Context, refreshToken string) (*dto.RefreshAccessTokenResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 *dto.RefreshAccessTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*dto.RefreshAccessTokenResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *dto.RefreshAccessTokenResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RefreshAccessTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockusecases_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type Mockusecases_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Mockusecases_Expecter) RefreshAccessToken(ctx interface{}, refreshToken interface{}) *Mockusecases_RefreshAccessToken_Call {
	return &Mockusecases_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, refreshToken)}
}

func (_c *Mockusecases_RefreshAccessToken_Call) Run(run func(ctx context.Context, refreshToken string)) *Mockusecases_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockusecases_RefreshAccessToken_Call) Return(refreshAccessTokenResponse *dto.RefreshAccessTokenResponse, err error) *Mockusecases_RefreshAccessToken_Call {
	_c.Call.Return(refreshAccessTokenResponse, err)
	return _c
}

func (_c *Mockusecases_RefreshAccessToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*dto.RefreshAccessTokenResponse, error)) *Mockusecases_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePasswordStrength provides a mock function for the type Mockusecases
func (_mock *Mockusecases) ValidatePasswordStrength(ctx context.Context, input *dto.ValidatePasswordInput) bool {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePasswordStrength")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.ValidatePasswordInput) bool); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mockusecases_ValidatePasswordStrength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePasswordStrength'
type Mockusecases_ValidatePasswordStrength_Call struct {
	*mock.Call
}

// ValidatePasswordStrength is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dto.ValidatePasswordInput
func (_e *Mockusecases_Expecter) ValidatePasswordStrength(ctx interface{}, input interface{}) *Mockusecases_ValidatePasswordStrength_Call {
	return &Mockusecases_ValidatePasswordStrength_Call{Call: _e.mock.On("ValidatePasswordStrength", ctx, input)}
}

func (_c *Mockusecases_ValidatePasswordStrength_Call) Run(run func(ctx context.Context, input *dto.ValidatePasswordInput)) *Mockusecases_ValidatePasswordStrength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.ValidatePasswordInput
		if args[1] != nil {
			arg1 = args[1].(*dto.ValidatePasswordInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockusecases_ValidatePasswordStrength_Call) Return(b bool) *Mockusecases_ValidatePasswordStrength_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mockusecases_ValidatePasswordStrength_Call) RunAndReturn(run func(ctx context.Context, input *dto.ValidatePasswordInput) bool) *Mockusecases_ValidatePasswordStrength_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyOTP provides a mock function for the type Mockusecases
func (_mock *Mockusecases) VerifyOTP(ctx context.Context, input *dto.VerifyOTPInput) (*dto.AuthResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 *dto.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.VerifyOTPInput) (*dto.AuthResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.VerifyOTPInput) *dto.AuthResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.VerifyOTPInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockusecases_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type Mockusecases_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dto.VerifyOTPInput
func (_e *Mockusecases_Expecter) VerifyOTP(ctx interface{}, input interface{}) *Mockusecases_VerifyOTP_Call {
	return &Mockusecases_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, input)}
}

func (_c *Mockusecases_VerifyOTP_Call) Run(run func(ctx context.Context, input *dto.VerifyOTPInput)) *Mockusecases_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.VerifyOTPInput
		if args[1] != nil {
			arg1 = args[1].(*dto.VerifyOTPInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockusecases_VerifyOTP_Call) Return(authResponse *dto.AuthResponse, err error) *Mockusecases_VerifyOTP_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *Mockusecases_VerifyOTP_Call) RunAndReturn(run func(ctx context.Context, input *dto.VerifyOTPInput) (*dto.AuthResponse, error)) *Mockusecases_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}
