// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/domain"
	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/dto"
	"github.com/cmmasaba/prototypes/urlshortener/pkg/infrastructure/services/tasks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockrepo creates a new instance of Mockrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepo {
	mock := &Mockrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockrepo is an autogenerated mock type for the repo type
type Mockrepo struct {
	mock.Mock
}

type Mockrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockrepo) EXPECT() *Mockrepo_Expecter {
	return &Mockrepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type Mockrepo
func (_mock *Mockrepo) CreateUser(ctx context.Context, input *domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Mockrepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.User
func (_e *Mockrepo_Expecter) CreateUser(ctx interface{}, input interface{}) *Mockrepo_CreateUser_Call {
	return &Mockrepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, input)}
}

func (_c *Mockrepo_CreateUser_Call) Run(run func(ctx context.Context, input *domain.User)) *Mockrepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_CreateUser_Call) Return(user *domain.User, err error) *Mockrepo_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Mockrepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, input *domain.User) (*domain.User, error)) *Mockrepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByTokenHash provides a mock function for the type Mockrepo
func (_mock *Mockrepo) GetRefreshTokenByTokenHash(ctx context.Context, token string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_GetRefreshTokenByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByTokenHash'
type Mockrepo_GetRefreshTokenByTokenHash_Call struct {
	*mock.Call
}

// GetRefreshTokenByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Mockrepo_Expecter) GetRefreshTokenByTokenHash(ctx interface{}, token interface{}) *Mockrepo_GetRefreshTokenByTokenHash_Call {
	return &Mockrepo_GetRefreshTokenByTokenHash_Call{Call: _e.mock.On("GetRefreshTokenByTokenHash", ctx, token)}
}

func (_c *Mockrepo_GetRefreshTokenByTokenHash_Call) Run(run func(ctx context.Context, token string)) *Mockrepo_GetRefreshTokenByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_GetRefreshTokenByTokenHash_Call) Return(refreshToken *domain.RefreshToken, err error) *Mockrepo_GetRefreshTokenByTokenHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *Mockrepo_GetRefreshTokenByTokenHash_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.RefreshToken, error)) *Mockrepo_GetRefreshTokenByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type Mockrepo
func (_mock *Mockrepo) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type Mockrepo_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Mockrepo_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *Mockrepo_GetUserByEmail_Call {
	return &Mockrepo_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *Mockrepo_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Mockrepo_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_GetUserByEmail_Call) Return(user *domain.User, err error) *Mockrepo_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Mockrepo_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *Mockrepo_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type Mockrepo
func (_mock *Mockrepo) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Mockrepo_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *Mockrepo_Expecter) GetUserByID(ctx interface{}, id interface{}) *Mockrepo_GetUserByID_Call {
	return &Mockrepo_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *Mockrepo_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *Mockrepo_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_GetUserByID_Call) Return(user *domain.User, err error) *Mockrepo_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Mockrepo_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *Mockrepo_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByPublicID provides a mock function for the type Mockrepo
func (_mock *Mockrepo) GetUserByPublicID(ctx context.Context, publicID string) (*domain.User, error) {
	ret := _mock.Called(ctx, publicID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByPublicID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, publicID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, publicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, publicID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_GetUserByPublicID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByPublicID'
type Mockrepo_GetUserByPublicID_Call struct {
	*mock.Call
}

// GetUserByPublicID is a helper method to define mock.On call
//   - ctx context.Context
//   - publicID string
func (_e *Mockrepo_Expecter) GetUserByPublicID(ctx interface{}, publicID interface{}) *Mockrepo_GetUserByPublicID_Call {
	return &Mockrepo_GetUserByPublicID_Call{Call: _e.mock.On("GetUserByPublicID", ctx, publicID)}
}

func (_c *Mockrepo_GetUserByPublicID_Call) Run(run func(ctx context.Context, publicID string)) *Mockrepo_GetUserByPublicID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_GetUserByPublicID_Call) Return(user *domain.User, err error) *Mockrepo_GetUserByPublicID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Mockrepo_GetUserByPublicID_Call) RunAndReturn(run func(ctx context.Context, publicID string) (*domain.User, error)) *Mockrepo_GetUserByPublicID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type Mockrepo
func (_mock *Mockrepo) RevokeRefreshToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockrepo_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type Mockrepo_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Mockrepo_Expecter) RevokeRefreshToken(ctx interface{}, token interface{}) *Mockrepo_RevokeRefreshToken_Call {
	return &Mockrepo_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, token)}
}

func (_c *Mockrepo_RevokeRefreshToken_Call) Run(run func(ctx context.Context, token string)) *Mockrepo_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_RevokeRefreshToken_Call) Return(err error) *Mockrepo_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockrepo_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *Mockrepo_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function for the type Mockrepo
func (_mock *Mockrepo) SaveRefreshToken(ctx context.Context, input domain.RefreshToken) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RefreshToken) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockrepo_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type Mockrepo_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.RefreshToken
func (_e *Mockrepo_Expecter) SaveRefreshToken(ctx interface{}, input interface{}) *Mockrepo_SaveRefreshToken_Call {
	return &Mockrepo_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, input)}
}

func (_c *Mockrepo_SaveRefreshToken_Call) Run(run func(ctx context.Context, input domain.RefreshToken)) *Mockrepo_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(domain.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_SaveRefreshToken_Call) Return(err error) *Mockrepo_SaveRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockrepo_SaveRefreshToken_Call) RunAndReturn(run func(ctx context.Context, input domain.RefreshToken) error) *Mockrepo_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockhibp creates a new instance of Mockhibp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockhibp(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockhibp {
	mock := &Mockhibp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockhibp is an autogenerated mock type for the hibp type
type Mockhibp struct {
	mock.Mock
}

type Mockhibp_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockhibp) EXPECT() *Mockhibp_Expecter {
	return &Mockhibp_Expecter{mock: &_m.Mock}
}

// CheckPasswordIsBreached provides a mock function for the type Mockhibp
func (_mock *Mockhibp) CheckPasswordIsBreached(ctx context.Context, password string) (bool, error) {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for CheckPasswordIsBreached")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockhibp_CheckPasswordIsBreached_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPasswordIsBreached'
type Mockhibp_CheckPasswordIsBreached_Call struct {
	*mock.Call
}

// CheckPasswordIsBreached is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *Mockhibp_Expecter) CheckPasswordIsBreached(ctx interface{}, password interface{}) *Mockhibp_CheckPasswordIsBreached_Call {
	return &Mockhibp_CheckPasswordIsBreached_Call{Call: _e.mock.On("CheckPasswordIsBreached", ctx, password)}
}

func (_c *Mockhibp_CheckPasswordIsBreached_Call) Run(run func(ctx context.Context, password string)) *Mockhibp_CheckPasswordIsBreached_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockhibp_CheckPasswordIsBreached_Call) Return(b bool, err error) *Mockhibp_CheckPasswordIsBreached_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Mockhibp_CheckPasswordIsBreached_Call) RunAndReturn(run func(ctx context.Context, password string) (bool, error)) *Mockhibp_CheckPasswordIsBreached_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockotp creates a new instance of Mockotp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockotp(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockotp {
	mock := &Mockotp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockotp is an autogenerated mock type for the otp type
type Mockotp struct {
	mock.Mock
}

type Mockotp_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockotp) EXPECT() *Mockotp_Expecter {
	return &Mockotp_Expecter{mock: &_m.Mock}
}

// GenerateOTP provides a mock function for the type Mockotp
func (_mock *Mockotp) GenerateOTP(ctx context.Context, userID string, purpose dto.OTPPurpose) (string, error) {
	ret := _mock.Called(ctx, userID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.OTPPurpose) (string, error)); ok {
		return returnFunc(ctx, userID, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.OTPPurpose) string); ok {
		r0 = returnFunc(ctx, userID, purpose)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.OTPPurpose) error); ok {
		r1 = returnFunc(ctx, userID, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockotp_GenerateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTP'
type Mockotp_GenerateOTP_Call struct {
	*mock.Call
}

// GenerateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - purpose dto.OTPPurpose
func (_e *Mockotp_Expecter) GenerateOTP(ctx interface{}, userID interface{}, purpose interface{}) *Mockotp_GenerateOTP_Call {
	return &Mockotp_GenerateOTP_Call{Call: _e.mock.On("GenerateOTP", ctx, userID, purpose)}
}

func (_c *Mockotp_GenerateOTP_Call) Run(run func(ctx context.Context, userID string, purpose dto.OTPPurpose)) *Mockotp_GenerateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.OTPPurpose
		if args[2] != nil {
			arg2 = args[2].(dto.OTPPurpose)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Mockotp_GenerateOTP_Call) Return(s string, err error) *Mockotp_GenerateOTP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Mockotp_GenerateOTP_Call) RunAndReturn(run func(ctx context.Context, userID string, purpose dto.OTPPurpose) (string, error)) *Mockotp_GenerateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTPByCodeAndUserID provides a mock function for the type Mockotp
func (_mock *Mockotp) GetOTPByCodeAndUserID(ctx context.Context, code string, userPublicID string, purpose dto.OTPPurpose) (*domain.OTP, error) {
	ret := _mock.Called(ctx, code, userPublicID, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetOTPByCodeAndUserID")
	}

	var r0 *domain.OTP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.OTPPurpose) (*domain.OTP, error)); ok {
		return returnFunc(ctx, code, userPublicID, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.OTPPurpose) *domain.OTP); ok {
		r0 = returnFunc(ctx, code, userPublicID, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OTP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, dto.OTPPurpose) error); ok {
		r1 = returnFunc(ctx, code, userPublicID, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockotp_GetOTPByCodeAndUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTPByCodeAndUserID'
type Mockotp_GetOTPByCodeAndUserID_Call struct {
	*mock.Call
}

// GetOTPByCodeAndUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - userPublicID string
//   - purpose dto.OTPPurpose
func (_e *Mockotp_Expecter) GetOTPByCodeAndUserID(ctx interface{}, code interface{}, userPublicID interface{}, purpose interface{}) *Mockotp_GetOTPByCodeAndUserID_Call {
	return &Mockotp_GetOTPByCodeAndUserID_Call{Call: _e.mock.On("GetOTPByCodeAndUserID", ctx, code, userPublicID, purpose)}
}

func (_c *Mockotp_GetOTPByCodeAndUserID_Call) Run(run func(ctx context.Context, code string, userPublicID string, purpose dto.OTPPurpose)) *Mockotp_GetOTPByCodeAndUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 dto.OTPPurpose
		if args[3] != nil {
			arg3 = args[3].(dto.OTPPurpose)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Mockotp_GetOTPByCodeAndUserID_Call) Return(oTP *domain.OTP, err error) *Mockotp_GetOTPByCodeAndUserID_Call {
	_c.Call.Return(oTP, err)
	return _c
}

func (_c *Mockotp_GetOTPByCodeAndUserID_Call) RunAndReturn(run func(ctx context.Context, code string, userPublicID string, purpose dto.OTPPurpose) (*domain.OTP, error)) *Mockotp_GetOTPByCodeAndUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllOTPsForUser provides a mock function for the type Mockotp
func (_mock *Mockotp) RevokeAllOTPsForUser(ctx context.Context, user string, purpose dto.OTPPurpose) error {
	ret := _mock.Called(ctx, user, purpose)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllOTPsForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.OTPPurpose) error); ok {
		r0 = returnFunc(ctx, user, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockotp_RevokeAllOTPsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllOTPsForUser'
type Mockotp_RevokeAllOTPsForUser_Call struct {
	*mock.Call
}

// RevokeAllOTPsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - purpose dto.OTPPurpose
func (_e *Mockotp_Expecter) RevokeAllOTPsForUser(ctx interface{}, user interface{}, purpose interface{}) *Mockotp_RevokeAllOTPsForUser_Call {
	return &Mockotp_RevokeAllOTPsForUser_Call{Call: _e.mock.On("RevokeAllOTPsForUser", ctx, user, purpose)}
}

func (_c *Mockotp_RevokeAllOTPsForUser_Call) Run(run func(ctx context.Context, user string, purpose dto.OTPPurpose)) *Mockotp_RevokeAllOTPsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.OTPPurpose
		if args[2] != nil {
			arg2 = args[2].(dto.OTPPurpose)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Mockotp_RevokeAllOTPsForUser_Call) Return(err error) *Mockotp_RevokeAllOTPsForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockotp_RevokeAllOTPsForUser_Call) RunAndReturn(run func(ctx context.Context, user string, purpose dto.OTPPurpose) error) *Mockotp_RevokeAllOTPsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockbackgroundTasks creates a new instance of MockbackgroundTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockbackgroundTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockbackgroundTasks {
	mock := &MockbackgroundTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockbackgroundTasks is an autogenerated mock type for the backgroundTasks type
type MockbackgroundTasks struct {
	mock.Mock
}

type MockbackgroundTasks_Expecter struct {
	mock *mock.Mock
}

func (_m *MockbackgroundTasks) EXPECT() *MockbackgroundTasks_Expecter {
	return &MockbackgroundTasks_Expecter{mock: &_m.Mock}
}

// NewEmailDeliveryTask provides a mock function for the type MockbackgroundTasks
func (_mock *MockbackgroundTasks) NewEmailDeliveryTask(ctx context.Context, input tasks.EmailDeliveryPayload, priority tasks.Priority) error {
	ret := _mock.Called(ctx, input, priority)

	if len(ret) == 0 {
		panic("no return value specified for NewEmailDeliveryTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, tasks.EmailDeliveryPayload, tasks.Priority) error); ok {
		r0 = returnFunc(ctx, input, priority)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockbackgroundTasks_NewEmailDeliveryTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEmailDeliveryTask'
type MockbackgroundTasks_NewEmailDeliveryTask_Call struct {
	*mock.Call
}

// NewEmailDeliveryTask is a helper method to define mock.On call
//   - ctx context.Context
//   - input tasks.EmailDeliveryPayload
//   - priority tasks.Priority
func (_e *MockbackgroundTasks_Expecter) NewEmailDeliveryTask(ctx interface{}, input interface{}, priority interface{}) *MockbackgroundTasks_NewEmailDeliveryTask_Call {
	return &MockbackgroundTasks_NewEmailDeliveryTask_Call{Call: _e.mock.On("NewEmailDeliveryTask", ctx, input, priority)}
}

func (_c *MockbackgroundTasks_NewEmailDeliveryTask_Call) Run(run func(ctx context.Context, input tasks.EmailDeliveryPayload, priority tasks.Priority)) *MockbackgroundTasks_NewEmailDeliveryTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tasks.EmailDeliveryPayload
		if args[1] != nil {
			arg1 = args[1].(tasks.EmailDeliveryPayload)
		}
		var arg2 tasks.Priority
		if args[2] != nil {
			arg2 = args[2].(tasks.Priority)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockbackgroundTasks_NewEmailDeliveryTask_Call) Return(err error) *MockbackgroundTasks_NewEmailDeliveryTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockbackgroundTasks_NewEmailDeliveryTask_Call) RunAndReturn(run func(ctx context.Context, input tasks.EmailDeliveryPayload, priority tasks.Priority) error) *MockbackgroundTasks_NewEmailDeliveryTask_Call {
	_c.Call.Return(run)
	return _c
}
