// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockrepo creates a new instance of Mockrepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepo {
	mock := &Mockrepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockrepo is an autogenerated mock type for the repo type
type Mockrepo struct {
	mock.Mock
}

type Mockrepo_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockrepo) EXPECT() *Mockrepo_Expecter {
	return &Mockrepo_Expecter{mock: &_m.Mock}
}

// CreateShortLink provides a mock function for the type Mockrepo
func (_mock *Mockrepo) CreateShortLink(ctx context.Context, input domain.Link) (*domain.Link, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortLink")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Link) (*domain.Link, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Link) *domain.Link); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Link) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_CreateShortLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortLink'
type Mockrepo_CreateShortLink_Call struct {
	*mock.Call
}

// CreateShortLink is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.Link
func (_e *Mockrepo_Expecter) CreateShortLink(ctx interface{}, input interface{}) *Mockrepo_CreateShortLink_Call {
	return &Mockrepo_CreateShortLink_Call{Call: _e.mock.On("CreateShortLink", ctx, input)}
}

func (_c *Mockrepo_CreateShortLink_Call) Run(run func(ctx context.Context, input domain.Link)) *Mockrepo_CreateShortLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Link
		if args[1] != nil {
			arg1 = args[1].(domain.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_CreateShortLink_Call) Return(link *domain.Link, err error) *Mockrepo_CreateShortLink_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *Mockrepo_CreateShortLink_Call) RunAndReturn(run func(ctx context.Context, input domain.Link) (*domain.Link, error)) *Mockrepo_CreateShortLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByCode provides a mock function for the type Mockrepo
func (_mock *Mockrepo) GetLinkByCode(ctx context.Context, code string) (*domain.Link, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByCode")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepo_GetLinkByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByCode'
type Mockrepo_GetLinkByCode_Call struct {
	*mock.Call
}

// GetLinkByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *Mockrepo_Expecter) GetLinkByCode(ctx interface{}, code interface{}) *Mockrepo_GetLinkByCode_Call {
	return &Mockrepo_GetLinkByCode_Call{Call: _e.mock.On("GetLinkByCode", ctx, code)}
}

func (_c *Mockrepo_GetLinkByCode_Call) Run(run func(ctx context.Context, code string)) *Mockrepo_GetLinkByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepo_GetLinkByCode_Call) Return(link *domain.Link, err error) *Mockrepo_GetLinkByCode_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *Mockrepo_GetLinkByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*domain.Link, error)) *Mockrepo_GetLinkByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcache creates a new instance of Mockcache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockcache {
	mock := &Mockcache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockcache is an autogenerated mock type for the cache type
type Mockcache struct {
	mock.Mock
}

type Mockcache_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockcache) EXPECT() *Mockcache_Expecter {
	return &Mockcache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type Mockcache
func (_mock *Mockcache) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockcache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Mockcache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Mockcache_Expecter) Get(ctx interface{}, key interface{}) *Mockcache_Get_Call {
	return &Mockcache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *Mockcache_Get_Call) Run(run func(ctx context.Context, key string)) *Mockcache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockcache_Get_Call) Return(bytes []byte, err error) *Mockcache_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Mockcache_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *Mockcache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type Mockcache
func (_mock *Mockcache) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockcache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Mockcache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *Mockcache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *Mockcache_Set_Call {
	return &Mockcache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *Mockcache_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *Mockcache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Mockcache_Set_Call) Return(err error) *Mockcache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockcache_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) error) *Mockcache_Set_Call {
	_c.Call.Return(run)
	return _c
}
