// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

type Mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockrepository) EXPECT() *Mockrepository_Expecter {
	return &Mockrepository_Expecter{mock: &_m.Mock}
}

// PingDB provides a mock function for the type Mockrepository
func (_mock *Mockrepository) PingDB(context1 context.Context) bool {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for PingDB")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mockrepository_PingDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingDB'
type Mockrepository_PingDB_Call struct {
	*mock.Call
}

// PingDB is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Mockrepository_Expecter) PingDB(context1 interface{}) *Mockrepository_PingDB_Call {
	return &Mockrepository_PingDB_Call{Call: _e.mock.On("PingDB", context1)}
}

func (_c *Mockrepository_PingDB_Call) Run(run func(context1 context.Context)) *Mockrepository_PingDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mockrepository_PingDB_Call) Return(b bool) *Mockrepository_PingDB_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mockrepository_PingDB_Call) RunAndReturn(run func(context1 context.Context) bool) *Mockrepository_PingDB_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockqueue creates a new instance of Mockqueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockqueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockqueue {
	mock := &Mockqueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockqueue is an autogenerated mock type for the queue type
type Mockqueue struct {
	mock.Mock
}

type Mockqueue_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockqueue) EXPECT() *Mockqueue_Expecter {
	return &Mockqueue_Expecter{mock: &_m.Mock}
}

// PingQueue provides a mock function for the type Mockqueue
func (_mock *Mockqueue) PingQueue(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingQueue")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mockqueue_PingQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingQueue'
type Mockqueue_PingQueue_Call struct {
	*mock.Call
}

// PingQueue is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Mockqueue_Expecter) PingQueue(ctx interface{}) *Mockqueue_PingQueue_Call {
	return &Mockqueue_PingQueue_Call{Call: _e.mock.On("PingQueue", ctx)}
}

func (_c *Mockqueue_PingQueue_Call) Run(run func(ctx context.Context)) *Mockqueue_PingQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mockqueue_PingQueue_Call) Return(b bool) *Mockqueue_PingQueue_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mockqueue_PingQueue_Call) RunAndReturn(run func(ctx context.Context) bool) *Mockqueue_PingQueue_Call {
	_c.Call.Return(run)
	return _c
}
