// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/domain"
	"github.com/cmmasaba/prototypes/urlshortener/pkg/application/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

type Mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockrepository) EXPECT() *Mockrepository_Expecter {
	return &Mockrepository_Expecter{mock: &_m.Mock}
}

// CreateOTP provides a mock function for the type Mockrepository
func (_mock *Mockrepository) CreateOTP(ctx context.Context, input *domain.OTP) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.OTP) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockrepository_CreateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOTP'
type Mockrepository_CreateOTP_Call struct {
	*mock.Call
}

// CreateOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - input *domain.OTP
func (_e *Mockrepository_Expecter) CreateOTP(ctx interface{}, input interface{}) *Mockrepository_CreateOTP_Call {
	return &Mockrepository_CreateOTP_Call{Call: _e.mock.On("CreateOTP", ctx, input)}
}

func (_c *Mockrepository_CreateOTP_Call) Run(run func(ctx context.Context, input *domain.OTP)) *Mockrepository_CreateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.OTP
		if args[1] != nil {
			arg1 = args[1].(*domain.OTP)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepository_CreateOTP_Call) Return(err error) *Mockrepository_CreateOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockrepository_CreateOTP_Call) RunAndReturn(run func(ctx context.Context, input *domain.OTP) error) *Mockrepository_CreateOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTPByCodeAndUser provides a mock function for the type Mockrepository
func (_mock *Mockrepository) GetOTPByCodeAndUser(ctx context.Context, code string, user string, purpose dto.OTPPurpose) (*domain.OTP, error) {
	ret := _mock.Called(ctx, code, user, purpose)

	if len(ret) == 0 {
		panic("no return value specified for GetOTPByCodeAndUser")
	}

	var r0 *domain.OTP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.OTPPurpose) (*domain.OTP, error)); ok {
		return returnFunc(ctx, code, user, purpose)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, dto.OTPPurpose) *domain.OTP); ok {
		r0 = returnFunc(ctx, code, user, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OTP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, dto.OTPPurpose) error); ok {
		r1 = returnFunc(ctx, code, user, purpose)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepository_GetOTPByCodeAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTPByCodeAndUser'
type Mockrepository_GetOTPByCodeAndUser_Call struct {
	*mock.Call
}

// GetOTPByCodeAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - user string
//   - purpose dto.OTPPurpose
func (_e *Mockrepository_Expecter) GetOTPByCodeAndUser(ctx interface{}, code interface{}, user interface{}, purpose interface{}) *Mockrepository_GetOTPByCodeAndUser_Call {
	return &Mockrepository_GetOTPByCodeAndUser_Call{Call: _e.mock.On("GetOTPByCodeAndUser", ctx, code, user, purpose)}
}

func (_c *Mockrepository_GetOTPByCodeAndUser_Call) Run(run func(ctx context.Context, code string, user string, purpose dto.OTPPurpose)) *Mockrepository_GetOTPByCodeAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 dto.OTPPurpose
		if args[3] != nil {
			arg3 = args[3].(dto.OTPPurpose)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Mockrepository_GetOTPByCodeAndUser_Call) Return(oTP *domain.OTP, err error) *Mockrepository_GetOTPByCodeAndUser_Call {
	_c.Call.Return(oTP, err)
	return _c
}

func (_c *Mockrepository_GetOTPByCodeAndUser_Call) RunAndReturn(run func(ctx context.Context, code string, user string, purpose dto.OTPPurpose) (*domain.OTP, error)) *Mockrepository_GetOTPByCodeAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllOTPsForUser provides a mock function for the type Mockrepository
func (_mock *Mockrepository) RevokeAllOTPsForUser(ctx context.Context, user string, purpose string) error {
	ret := _mock.Called(ctx, user, purpose)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllOTPsForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, user, purpose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Mockrepository_RevokeAllOTPsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllOTPsForUser'
type Mockrepository_RevokeAllOTPsForUser_Call struct {
	*mock.Call
}

// RevokeAllOTPsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user string
//   - purpose string
func (_e *Mockrepository_Expecter) RevokeAllOTPsForUser(ctx interface{}, user interface{}, purpose interface{}) *Mockrepository_RevokeAllOTPsForUser_Call {
	return &Mockrepository_RevokeAllOTPsForUser_Call{Call: _e.mock.On("RevokeAllOTPsForUser", ctx, user, purpose)}
}

func (_c *Mockrepository_RevokeAllOTPsForUser_Call) Run(run func(ctx context.Context, user string, purpose string)) *Mockrepository_RevokeAllOTPsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Mockrepository_RevokeAllOTPsForUser_Call) Return(err error) *Mockrepository_RevokeAllOTPsForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Mockrepository_RevokeAllOTPsForUser_Call) RunAndReturn(run func(ctx context.Context, user string, purpose string) error) *Mockrepository_RevokeAllOTPsForUser_Call {
	_c.Call.Return(run)
	return _c
}
